services:
  - type: web
    name: booklyn-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    rootContext: backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URL
        value: mongodb+srv://gracefulandrei_db_user:jatgmOrnltb2hEO0@cluster0.emd6opx.mongodb.net/?appName=Cluster0
      - key: DATABASE_URL
        fromDatabase:
          name: booklyn-db
          property: connectionString

databases:
  - name: booklyn-db
    plan: free
